name: avataaar_image
description: Flutter wrapper widget for Avataaars API allowing to generate and display avatar images.
version: 1.0.9
homepage: https://github.com/tomwyr/avataaar-image/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.21.0-nullsafety.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
